### PR TITLE
Add prefix to examples

### PR DESCRIPTION
**Pull request by kyleholzinger**
This mimics the formatting on any of the rules pages, and adds the rule name as a prefix to each of the example line items

## TSLint Docs:
rule semicolon 2017-05-03 15-04-21

##### Examples

```json
 [true, "check-branch", "check-operator", "check-typecast"]
```
##### Examples

```json
"whitespace": [true, "check-branch", "check-operator", "check-typecast"]
```

### CODE REVIEW

**Comment by tkqubo** [comment]
Sorry for my late review.   But thanks so much for your PR, it LGTM.

**Comment by tkqubo** [comment]
@kyleholzinger

**Comment by kyleholzinger** [comment]
No worries. Thanks for the merge @tkqubo !

**Comment by kyleholzinger** [comment]
Once we make a new release, we should be able to fix peoples' problems in #4 with the other tslint presets

**Pull request merged**
