### PR TITLE
Updates to Dockerfile, typescript 2.0, and removing typings

### PR DESCRIPTION
**Pull request by brantw**
I made some tweaks to the Dockerfile and I am able to run codeclimate-tslint on both macOS and CentOS 7 using `codeclimate analyze --dev`.  I think issue #4 should be resolved.

@amcdnl also upgraded the project to Typescript 2.0 and removed typings, as well as a few other changes.  This should satisfy issue #5.

### CODE REVIEW

**Comment by amcdnl** [comment]
FYI @mrb :)

**Comment by tkqubo** [comment]
Thanks so much for your great contribution!   I really appreciate that.  

In my mac os environment, after changing `tsconfig.json`'s `compilerOptions.target` to `es5`,
`codeclimate analyze --dev` did work (node version is `v6.3.1`).   Do I need something else to run with `es6` output option? @brantw 

Anyway I will happily merge this PR, thanks again

**Comment by brantw** [comment]
@tkqubo Sorry I missed your comment.  I didn't have to drop down to `es5` to run on my Mac, I was able to run `codeclimate analyze --dev` with `es6`.

**Comment by tkqubo** [comment]
Oh, I see. but on my Mac environment, when I build docker image with `es6` option, it emits a syntax error like the one below:

```bash
$ docker build --rm -t codeclimate/codeclimate-tslint .
...
$ codeclimate analyze --dev

Starting analysis
Running tslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine tslint:stable failed with status 1 and stderr
/usr/src/app/dist/fileMatcher.js:18
        let [directories, files] = _.partition(expandedExcludePaths, file => fs.lstatSync(file).isDirectory());
            ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/src/app/dist/tsLinter.js:8:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

While with `es5` option it worked.  Thanks anyway, I will try some more :-)

**Pull request merged**
