### PR TITLE
Adding support for running prettier with tslint

### PR DESCRIPTION
**Pull request by neoncrisis**
My team has been using tslint with codeclimate for a while and we want to add prettier to our project, but are running into an issue due to lack of prettier support.

This PR also addresses the request in this issue: https://github.com/tkqubo/codeclimate-tslint/issues/30

- Adds [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier) to allow playing nicely with [prettier](https://github.com/prettier/prettier).
- Adds [tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier) which adds a new `prettier` rule to run and report prettier errors through tslint.  This rule is not set by default so won't affect any users not using prettier.
- Adds [prettier](https://github.com/prettier/prettier) as a dependency to support `tslint-plugin-prettier`.

To use `tslint-config-prettier`:
Extend `"tslint-config-prettier"` is tslint.json.

To use `tslint-plugin-prettier`:
Add `"tslint-plugin-prettier"` to `rulesDirectory` in tslint.json
Add `prettier: true` to `rules` in tslint.json

### CODE REVIEW

**Comment by fzxt** [comment]
any status on this? this would be awesome to have.

**Comment by tkqubo** [comment]
Thanks for the PR!

And I need some modifications in order to make them actually work (sorry, tslint in codeclimate-tslint currently doesn't load those plugins.  It's just used for referencing metadata)

**Comment by alvis** [comment]
Since this PR has been merged, may I ask when would it be released? At the moment I have to reference another tslint.json without `tslint-config-prettier` for cc. Not a great experience.

**Comment by ianks** [comment]
I would also like to see this deployed. Currently we get this error:

```
/usr/src/app/node_modules/tslint/lib/configuration.js:55
        throw new error_1.FatalError("Failed to load " + configPath + ": " + error.message, error);
        ^

FatalError: Failed to load /tmp/codeclimate-tslint/4402d6255ae37c94159e2942797c480f5e3209bdd457c4da31aa570f7fa8168e.json: Invalid "extends" configuration value - could not require "tslint-config-prettier". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
    at FatalError.Error (native)
    at new FatalError (/usr/src/app/node_modules/tslint/lib/error.js:27:28)
    at Object.findConfiguration (/usr/src/app/node_modules/tslint/lib/configuration.js:55:15)
    at new TsLinter (/usr/src/app/dist/tsLinter.js:33:57)
    at Object.<anonymous> (/usr/src/app/dist/index.js:26:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

This is our tslint.json:

```
{
  "extends": [
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
```

**Comment by arboleya** [comment]
@tkqubo Any news on this? Will it be deployed at some point? Tks

**Pull request merged**
